#include "MainWindow.h"
#include "core/AndroidRuntime.h"
#include "core/ResourceScheduler.h"
#include "core/ApiServer.h"
#include <QApplication>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QHeaderView>
#include <QPushButton>
#include <QComboBox>
#include <QFrame>
#include <QSplitter>
#include <QFont>
#include <QStyle>

namespace{
const char*style=R"(
QMainWindow,QWidget{background:#111318;color:#e7e9ee;font-family:"Noto Sans",sans-serif;font-size:13px;}
QFrame#sidebar,QFrame#inspector,QFrame#toolbar{background:#17191f;}
QLabel#brand{font-size:18px;font-weight:700;color:#fff;} QLabel#title{font-size:20px;font-weight:700;color:#fff;} QLabel#muted{color:#858b98;font-size:11px;} QLabel#cardTitle{font-size:10px;font-weight:700;color:#9da4b1;}
QPushButton#nav{border:0;border-radius:7px;text-align:left;padding:9px 12px;color:#aeb4c0;background:transparent;} QPushButton#nav:hover,QPushButton#nav[selected="true"]{background:#292e38;color:#fff;}
QPushButton#primary{background:#3f7cff;color:white;border:0;border-radius:7px;padding:7px 14px;font-weight:600;} QPushButton#secondary{background:#242832;color:#d9dce3;border:1px solid #343945;border-radius:7px;padding:7px 12px;}
QFrame#card{background:#191c23;border:1px solid #292d36;border-radius:10px;} QListWidget,QTableWidget,QTextEdit{background:#15171d;border:1px solid #292d36;border-radius:8px;color:#dfe2e8;} QListWidget::item{padding:9px;border-radius:6px;} QListWidget::item:selected{background:#292f3a;color:white;}
QHeaderView::section{background:#1c1f26;color:#8f96a3;border:0;padding:8px;font-size:11px;} QTableWidget::item{padding:7px;} QProgressBar{background:#242832;border:0;border-radius:4px;height:7px;} QProgressBar::chunk{background:#5b8cff;border-radius:4px;} QComboBox{background:#20232b;border:1px solid #30343e;border-radius:7px;padding:6px;color:#ddd;}
)";
QLabel*lab(const QString&t,const QString&n={}){auto*l=new QLabel(t);if(!n.isEmpty())l->setObjectName(n);return l;}
QFrame*card(const QString&t,const QString&v,const QString&s){auto*f=new QFrame;f->setObjectName("card");auto*x=new QVBoxLayout(f);x->setContentsMargins(14,12,14,12);x->addWidget(lab(t.toUpper(),"cardTitle"));x->addWidget(lab(v,"metric"));x->addWidget(lab(s,"muted"));return f;}
}
MainWindow::MainWindow(QWidget*p):QMainWindow(p){
 setWindowTitle("MobileLab Android · ARM64");resize(1460,900);setMinimumSize(1100,700);qApp->setStyleSheet(style);
 runtime_=new AndroidRuntime(this);scheduler_=new ResourceScheduler(this);api_=new ApiServer(runtime_,scheduler_,this);runtime_->probe();scheduler_->configure(8,16384);api_->listen(4000);
 connect(runtime_,&AndroidRuntime::logMessage,this,[this](const QString&m){if(console_)console_->append("[runtime] "+m);});
 connect(scheduler_,&ResourceScheduler::logMessage,this,[this](const QString&m){if(console_)console_->append("[scheduler] "+m);});
 auto*root=new QWidget;auto*hl=new QHBoxLayout(root);hl->setContentsMargins(0,0,0,0);hl->setSpacing(0);hl->addWidget(makeSidebar());
 auto*center=new QWidget;auto*cv=new QVBoxLayout(center);cv->setContentsMargins(0,0,0,0);cv->setSpacing(0);cv->addWidget(makeTopBar());pages_=new QStackedWidget;pages_->addWidget(makeDashboard());pages_->addWidget(makeDevices());pages_->addWidget(makeMatrix());pages_->addWidget(makeConsole());cv->addWidget(pages_,1);hl->addWidget(center,1);hl->addWidget(makeInspector());setCentralWidget(root);
 pollTimer_=new QTimer(this);connect(pollTimer_,&QTimer::timeout,this,[this]{if(runtime_){runtime_->refreshTargets();if(active_)active_->setText(QString("%1 Active").arg(std::count_if(runtime_->targets().begin(),runtime_->targets().end(),[](const AndroidTarget&t){return t.state=="running";})));}});pollTimer_->start(2000);
}
void MainWindow::selectPage(int i){if(pages_)pages_->setCurrentIndex(qBound(0,i,pages_->count()-1));}
QWidget*MainWindow::makeSidebar(){auto*f=new QFrame;f->setObjectName("sidebar");f->setFixedWidth(240);auto*v=new QVBoxLayout(f);v->setContentsMargins(14,18,14,14);v->addWidget(lab("MobileLab","brand"));v->addWidget(lab("ANDROID · ARM64 LINUX","muted"));v->addSpacing(18);QStringList ns={"⌘  Overview","▦  Devices","▤  Test Matrix","◌  Live Console"};for(int i=0;i<ns.size();++i){auto*b=new QPushButton(ns[i]);b->setObjectName("nav");b->setProperty("selected",i==0);connect(b,&QPushButton::clicked,this,[this,i]{selectPage(i);});v->addWidget(b);}v->addStretch();auto*c=new QFrame;c->setObjectName("card");auto*x=new QVBoxLayout(c);x->addWidget(lab("ARM64 RUNTIME","cardTitle"));x->addWidget(lab(runtime_&&runtime_->architecture().contains("arm")?"● ARM64 native":"● Runtime detected","muted"));x->addWidget(lab(runtime_&&runtime_->kvmAvailable()?"KVM available":"KVM unavailable · userspace mode","muted"));x->addWidget(lab("REST 127.0.0.1:4000","muted"));v->addWidget(c);return f;}
QWidget*MainWindow::makeTopBar(){auto*f=new QFrame;f->setObjectName("toolbar");f->setFixedHeight(58);auto*h=new QHBoxLayout(f);h->setContentsMargins(16,8,16,8);h->addWidget(lab("Android Device Lab","title"));h->addSpacing(16);auto*c=new QComboBox;c->addItems({"ARM64 Native Validation","Android Emulator Matrix","CI Validation Core"});c->setFixedWidth(220);h->addWidget(c);h->addStretch();connection_=lab(runtime_&&runtime_->kvmAvailable()?"● Connected · KVM":"● Connected · userspace ARM64","muted");h->addWidget(connection_);auto*b=new QPushButton("▶  Run Matrix");b->setObjectName("primary");connect(b,&QPushButton::clicked,this,[this]{scheduler_->enqueue("arm64-dev","android-test --api 35",1);});h->addWidget(b);return f;}
QWidget*MainWindow::makeDashboard(){auto*p=new QWidget;auto*v=new QVBoxLayout(p);v->setContentsMargins(22,22,22,18);v->addWidget(lab("Overview","title"));v->addWidget(lab("Android orchestration and ARM64 execution on Linux","muted"));auto*c=new QHBoxLayout;c->addWidget(card("Targets",QString::number(runtime_->targets().size()),"discovered / configured"));auto*a=card("Running","0","active workloads");active_=a->findChild<QLabel*>("metric");c->addWidget(a);c->addWidget(card("Queued","0","scheduler jobs"));c->addWidget(card("API","4000","local REST endpoint"));v->addLayout(c);auto*s=new QSplitter(Qt::Horizontal);auto*l=new QFrame;l->setObjectName("card");auto*lv=new QVBoxLayout(l);lv->addWidget(lab("DEVICE POOL","cardTitle"));deviceList_=new QListWidget;for(const auto&t:runtime_->targets())deviceList_->addItem(QString("%1 · Android %2 · %3 · %4").arg(t.id,t.api,t.arch,t.state));lv->addWidget(deviceList_);s->addWidget(l);auto*r=new QFrame;r->setObjectName("card");auto*rv=new QVBoxLayout(r);rv->addWidget(lab("HOST RESOURCES","cardTitle"));rv->addWidget(lab("CPU capacity","muted"));cpu_=new QProgressBar;cpu_->setValue(32);rv->addWidget(cpu_);rv->addWidget(lab("Memory capacity","muted"));memory_=new QProgressBar;memory_->setValue(48);rv->addWidget(memory_);rv->addSpacing(12);rv->addWidget(lab("EXECUTION POLICY","cardTitle"));rv->addWidget(lab(runtime_->kvmAvailable()?"KVM acceleration available.":"KVM is unavailable; virtualization-dependent workloads are kept out of the execution path.","muted"));rv->addStretch();s->addWidget(r);v->addWidget(s,1);return p;}
QWidget*MainWindow::makeDevices(){auto*p=new QWidget;auto*v=new QVBoxLayout(p);v->setContentsMargins(22,22,22,18);v->addWidget(lab("Devices","title"));v->addWidget(lab("Lifecycle management for Android targets","muted"));auto*l=new QListWidget;for(const auto&t:runtime_->targets())l->addItem(QString("%1     API %2     %3     %4").arg(t.id,t.api,t.arch,t.state));v->addWidget(l,1);return p;}
QWidget*MainWindow::makeMatrix(){auto*p=new QWidget;auto*v=new QVBoxLayout(p);v->setContentsMargins(22,22,22,18);v->addWidget(lab("Test Matrix","title"));v->addWidget(lab("Cross-version ARM64 validation","muted"));matrix_=new QTableWidget(5,5);matrix_->setHorizontalHeaderLabels({"Target","Android","Arch","Backend","Status"});QString d[5][5]={{"Pixel 9 Pro","15","arm64","native","PASS"},{"Pixel 8","14","arm64","native","PASS"},{"Tablet","15","arm64","userspace","READY"},{"CI Worker","15","arm64","native","PASS"},{"Compatibility","14–15","arm64","scheduler","QUEUED"}};for(int r=0;r<5;r++)for(int c=0;c<5;c++)matrix_->setItem(r,c,new QTableWidgetItem(d[r][c]));matrix_->horizontalHeader()->setSectionResizeMode(QHeaderView::Stretch);v->addWidget(matrix_,1);return p;}
QWidget*MainWindow::makeConsole(){auto*p=new QWidget;auto*v=new QVBoxLayout(p);v->setContentsMargins(22,22,22,18);v->addWidget(lab("Live Console","title"));v->addWidget(lab("Runtime, scheduler and API events","muted"));console_=new QTextEdit;console_->setReadOnly(true);console_->setFont(QFont("monospace",10));console_->setPlainText(QString("[MobileLab] Android ARM64 framework initialized.\n[probe] arch=%1\n[probe] KVM=%2\n[api] REST listening on 127.0.0.1:%3").arg(runtime_->architecture(),runtime_->kvmAvailable()?"available":"unavailable").arg(api_->port()));v->addWidget(console_,1);return p;}
QWidget*MainWindow::makeInspector(){auto*f=new QFrame;f->setObjectName("inspector");f->setFixedWidth(280);auto*v=new QVBoxLayout(f);v->setContentsMargins(14,18,14,14);v->addWidget(lab("Inspector","title"));v->addWidget(lab("RUNTIME","cardTitle"));auto*c=new QFrame;c->setObjectName("card");auto*x=new QVBoxLayout(c);x->addWidget(lab("Android ARM64 Runtime","brand"));x->addWidget(lab("Linux / ARM64","muted"));x->addWidget(lab(runtime_->qemuAvailable()?"QEMU: available":"QEMU: not installed","muted"));x->addWidget(lab(runtime_->emulatorAvailable()?"Android emulator: available":"Android emulator: not installed","muted"));v->addWidget(c);v->addWidget(lab("ACTIONS","cardTitle"));auto*run=new QPushButton("Start Selected Target");run->setObjectName("secondary");connect(run,&QPushButton::clicked,this,[this]{if(!runtime_->targets().isEmpty())runtime_->start(runtime_->targets().first().id);});v->addWidget(run);auto*stop=new QPushButton("Stop Selected Target");stop->setObjectName("secondary");connect(stop,&QPushButton::clicked,this,[this]{if(!runtime_->targets().isEmpty())runtime_->stop(runtime_->targets().first().id);});v->addWidget(stop);auto*shell=new QPushButton("Open Android Shell");shell->setObjectName("secondary");connect(shell,&QPushButton::clicked,this,[this]{if(!runtime_->targets().isEmpty())runtime_->shell(runtime_->targets().first().id,"getprop ro.product.cpu.abi");});v->addWidget(shell);v->addSpacing(14);v->addWidget(lab("API","cardTitle"));v->addWidget(lab("GET /status\nGET /devices\nPOST /runs\nPOST /devices/:id/start\nPOST /devices/:id/stop","muted"));v->addStretch();return f;}
