#include "ResourceScheduler.h"

ResourceScheduler::ResourceScheduler(QObject*p):QObject(p){connect(&m_timer,&QTimer::timeout,this,&ResourceScheduler::tick);m_timer.start(250);}
void ResourceScheduler::configure(int cpu,int memoryMb){m_cpu=qMax(1,cpu);m_memory=qMax(512,memoryMb);emit jobChanged();}
QString ResourceScheduler::enqueue(const QString&t,const QString&c,int cost){return submit(t,c,cost,0,0);}
QString ResourceScheduler::submit(const QString&t,const QString&c,int cost,int priority,int maxRetries){RunRequest r;r.id=QString("run-%1").arg(++m_seq);r.target=t;r.command=c;r.cost=qMax(1,cost);r.priority=qBound(0,priority,100);r.maxRetries=qMax(0,maxRetries);m_queue.push_back(r);m_logs<<QString("queued %1 on %2 (cost=%3 priority=%4 retries=%5)").arg(r.id,t).arg(r.cost).arg(r.priority).arg(r.maxRetries);emit logMessage(m_logs.last());emit jobChanged();return r.id;}
void ResourceScheduler::cancel(const QString&id){for(auto it=m_running.begin();it!=m_running.end();++it)if(it.key()==id){m_used-=it.value().cost;m_running.erase(it);emit logMessage("cancelled "+id);emit jobChanged();return;}for(int i=0;i<m_queue.size();++i)if(m_queue[i].id==id){m_queue.removeAt(i);emit logMessage("cancelled queued "+id);emit jobChanged();return;}emit jobChanged();}
int ResourceScheduler::nextRunnableIndex()const{int best=-1;for(int i=0;i<m_queue.size();++i){if(m_used+m_queue[i].cost>capacity())continue;if(best<0||m_queue[i].priority>m_queue[best].priority||m_queue[i].priority==m_queue[best].priority&&m_queue[i].id<m_queue[best].id)best=i;}return best;}
void ResourceScheduler::tick(){const int i=nextRunnableIndex();if(i<0)return;auto r=m_queue.takeAt(i);m_used+=r.cost;r.attempt++;m_running.insert(r.id,r);emit logMessage(QString("started %1: %2 (attempt=%3 priority=%4)").arg(r.id,r.command).arg(r.attempt).arg(r.priority));QTimer::singleShot(1500,[this,r]{auto current=m_running.take(r.id);if(current.id.isEmpty())return;m_used-=current.cost;emit logMessage("completed "+current.id);emit jobChanged();});emit jobChanged();}
QJsonObject ResourceScheduler::dryRun(const QString&t,const QString&c,int cost,int priority)const{const int normalized=qMax(1,cost);return {{"target",t},{"command",c},{"cost",normalized},{"priority",qBound(0,priority,100)},{"capacity",capacity()},{"used_cost",m_used},{"can_start_now",m_used+normalized<=capacity()},{"queued_ahead",m_queue.size()},{"estimated_slot_ms",m_used+normalized<=capacity()?0:1500}};}
QJsonObject ResourceScheduler::status()const{return {{"cpu",m_cpu},{"memory_mb",m_memory},{"queued",m_queue.size()},{"running",m_running.size()},{"used_cost",m_used},{"capacity",capacity()},{"features","priority,retry,dry-run"}};}
